apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-service
  template:
    metadata:
      labels:
        app: blob-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: blob-service
        image: //TODO: fix here
        ports:
        - containerPort: 3002
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        startupProbe:
          httpGet:
            path: /health
            port: 27017 
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 27017 
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 27017 
          failureThreshold: 5
          initialDelaySeconds: 3
          periodSeconds: 3
      initContainers:
      - name: wait-for-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done;']
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi