apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-service
  template:
    metadata:
      labels:
        app: tukano-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: tukano-service
        image: rafaelpires70068/scc2425-tukanoapp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -zv db-service 5432; do echo waiting for postgres; sleep 2; done;']
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
