apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: db-service
        image: postgres:latest
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 1m
            memory: 50Mi
          limits:
            cpu: 75m
            memory: 128Mi
        startupProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 5
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 5
        env:
        - name: POSTGRES_DB
          value: tukano
        - name: POSTGRES_USER
          value: sa
        - name: POSTGRES_PASSWORD